### ISSUE TITLE
【长】Useful Optional Extensions

### ISSUE THREAD

**Issue by sfmDev** [SwiftGGTeam/translation#110]
title: Useful Optional Extensions
date: 2018.01.10
tags: Swift
categories: Swift
permalink: http://appventure.me/2018/01/10/optional-extensions/

---

原文链接=
作者=
原文日期=
译者=
校对=
定稿=

**Comment by Rsenjoyer** [comment]
文章已经翻译完，这两天整理整理就提 PR， 文章有一些错误，提出来
在 Emptiness（判空）里面， 原作者使用如下代码
`extension Optional {
    /// Returns true if the optional is empty
    var isNone: Bool {
	return self == .none
    }

    /// Returns true if the optional is not empty
    var isSome: Bool {
	return self != .none
    }
}`

这种方式是存在错误的，改为
`extension Optional {
    /// 可选值为空的时候返回 true
    var isNone: Bool {
        switch self {
        case .none:
            return true
        case .some:
            return false
        }
    }

    /// 可选值非空返回 true
    var isSome: Bool {
        return !isNone
    }
}`
对应下面的一段解释也做了相应的删减调整

> 
Those are the most basic additions to the optional type. ........ Using optional.isSome feels much cleaner and less noisy than if optional == nil 
>

**Comment by Rsenjoyer** [comment]
https://github.com/SwiftGGTeam/translation/pull/142/files

**Comment by Rsenjoyer** [comment]
#142
