### ISSUE TITLE
【长】Expanding Swift's Reach

### ISSUE THREAD

**Issue by sfmDev** [SwiftGGTeam/translation#111]
title: Expanding Swift's Reach
date: 2018.05.03
tags: Swift
categories: Swift
permalink: http://appventure.me/2018/05/03/expanding-swifts-reach/

---

原文链接=
作者=
原文日期=
译者=
校对=
定稿=

**Comment by Adolf-L** [comment]
https://github.com/SwiftGGTeam/translation/pull/129
