### ISSUE TITLE
【中】 iOS: A Beautiful Way of Styling IBOutlets in Swift

### ISSUE THREAD

**Issue by sfmDev** [SwiftGGTeam/translation#112]
title: A Beautiful Way of Styling IBOutlets in Swift
date: 
tags: Swift
categories: UI
permalink: http://szulctomasz.com/blog/2016-06-22-a-beautiful-way-of-styling-iboutlets-in-swift/

---

原文链接=
作者=
原文日期=
译者=
校对=
定稿=

**Comment by numbbbbb** [comment]
文章被作者archive了，链接：http://szulctomasz.com/programming-blog/1/01/blog-archive-2017/，下载链接：http://szulctomasz.com/uploads/programming-blog/archive-09-05-2017.zip。

作者博客首页有说明：

```
All articles published before 9/May/2017 have been archived and are available right here. And here you can check out titles of the archived articles before you start to download them.
```

这里我们原文链接就写归档那个链接吧，毕竟没有原文。译者可以加一个说明，如果读者要看原文就去下载。

**Comment by numbbbbb** [comment]
另外就是确认下 @ennisk 有没有开始翻译，如果没有就发之前老的翻译，如果翻译了就正常走流程。
