### ISSUE TITLE
【中】Private properties in protocols

### ISSUE THREAD

**Issue by sfmDev** [SwiftGGTeam/translation#124]
title: Private properties in protocols
date: 2018-09-03
tags: Swift
categories: Swift
permalink: http://alisoftware.github.io/swift/protocols/2018/09/02/protocols-private-properties/

---

原文链接=
作者=
原文日期=
译者=
校对=
定稿=

**Comment by numbbbbb** [comment]
@dzyding 最好建个新分支提交，你提交的晚，校对肯定就晚，发布更晚。
