### ISSUE TITLE
【长】mac​OS Dynamic Desktop

### ISSUE THREAD

**Issue by mobilefellow** [SwiftGGTeam/translation#139]
title: mac​OS Dynamic Desktop
date: 2018.10.01
tags: Swift, NSHipster
categories: Swift, NSHipster
permalink: https://nshipster.com/macos-dynamic-desktop/

---

原文链接=
作者=
原文日期=
译者=
校对=
定稿=

**注意**，这是一篇 NSHipster 的文章，翻译时请参考 [NSHipster翻译说明](https://github.com/SwiftGGTeam/translation/blob/master/NSHipster翻译说明.md)。如有任何疑问，可以在 QQ/微信群里联系“雨谨”。

**Comment by saitjr** [comment]
#144
