### ISSUE TITLE
Compiling Open Source Swift Foundation（短）

### ISSUE THREAD

**Issue by saitjr** [SwiftGGTeam/translation#15]
http://dev.iachieved.it/iachievedit/compiling-open-source-swift-foundation/

**Comment by Rsenjoyer** [comment]
[](https://github.com/SwiftGGTeam/translation/pull/119)

**Comment by Rsenjoyer** [comment]
[https://github.com/SwiftGGTeam/translation/pull/119](https://github.com/SwiftGGTeam/translation/pull/119)

**Comment by Rsenjoyer** [comment]
一校完成，我也根据一校的建议进行了更改
