### ISSUE TITLE
【短】Prototyping CoreGraphics in the Playground

### ISSUE THREAD

**Issue by numbbbbb** [SwiftGGTeam/translation#169]
title: 
date: 
tags: 
categories: 
permalink: 

---

原文链接=https://ericasadun.com/2018/11/20/prototyping-coregraphics-in-the-playground/
作者=
原文日期=
译者=
校对=
定稿=

**Comment by SunsetWan** [comment]
这篇文章分享了一些关于 playground 优缺点的看法，整篇大多数的篇幅是作者个人的观点，而标题中的：“Prototyping CoreGraphics”的具体细节几乎没有。故我个人认为，没有多大的翻译价值。
