### ISSUE TITLE
【长】Protocol Oriented Programming in Swift: An Introduction

### ISSUE THREAD

**Issue by dzyding** [SwiftGGTeam/translation#170]
title:
date:
tags:
categories:
permalink:

原文链接=https://www.appcoda.com/protocol-oriented-programming/
作者=
原文日期=
译者=
校对=
定稿=

**Comment by dzyding** [comment]
期间处理几篇官方文档的翻译，之前翻译了一半的文件找不到了。。得重新翻译。

**Comment by numbbbbb** [comment]
辛苦了 😅

**Comment by dzyding** [comment]
已提交 pr
