### ISSUE TITLE
【短】The Beauty of Swift 5 String Interpolation

### ISSUE THREAD

**Issue by sfmDev** [SwiftGGTeam/translation#175]
title:  The Beauty of Swift 5 String Interpolation
date: 2018.12.12
tags: Swift
categories Swift:
permalink: https://ericasadun.com/2018/12/12/the-beauty-of-swift-5-string-interpolation/

---

原文链接=
作者=
原文日期=
译者=
校对=
定稿=

**Comment by BigNerdCoding** [comment]
有候选人翻译，勿认领
