### ISSUE TITLE
【长】NSPredicate

### ISSUE THREAD

**Issue by sfmDev** [SwiftGGTeam/translation#204]
title: NSPredicate
date: 
tags: 
categories: 
permalink: https://www.swiftjectivec.com/nspredicate-objective-c/

---

原文链接=
作者=
原文日期=
译者=
校对=
定稿=

**Comment by baileilei** [comment]
how to assign this to me?

**Comment by baileilei** [comment]
[](url)
I wonder how to assign this text to me？
> title: NSPredicate
> date:
> tags:
> categories:
> permalink: https://www.swiftjectivec.com/nspredicate-objective-c/
> 
> 原文链接=
> 作者=
> 原文日期=
> 译者=
> 校对=
> 定稿=

**Comment by numbbbbb** [comment]
翻译文章需要先加入翻译组，非翻译组成员没有权限。

**Comment by baileilei** [comment]
> 翻译文章需要先加入翻译组，非翻译组成员没有权限。
怎么加入呢？   找了好多没找到入口

**Comment by numbbbbb** [comment]
抱歉，暂时不招收新成员了。前段时间加入了一些新同学，目前我们有授权的博客更新也比较不频繁，所以目前是文章少人多。可以关注下我们的微博@SwiftGG翻译组，之后招人会在微博发布。
