### ISSUE TITLE
【长】Friday Q&A 2015-02-20: Let's Build @synchronized

### ISSUE THREAD

**Issue by saitjr** [SwiftGGTeam/translation#32]
https://www.mikeash.com/pyblog/friday-qa-2015-02-20-lets-build-synchronized.html

**Comment by Sunnyyoung** [comment]
# 构建一个 `@synchronized`

继续上一篇关于线程安全主题的文章，今天我将会在最新一版的 Let's Build 中探讨一下 Objective-C 的 `@synchronized` 的实现。我将会基于 Swift 来实现，尽管和 Objective-C 版本的差不多。

## 回顾

`@synchronized` 在 Objective-C 中是一种控制结构。它接受一个对象指针作为参数并且后面跟着一段代码块。对象指针充当锁，在任何时候 `@synchronized` 代码块中只允许有一个线程使用该对象指针。

这是一种使用锁进行多线程编程的简单方法。举个例子，你可以使用 `NSLock` 来保护对 NSMutableArray 的操作：

```objc
NSMutableArray *array;
NSLock *arrayLock;

[arrayLock lock];
[array addObject: obj];
[arrayLock unlock];
```

也可以使用 `@synchronized` 来将数组本身加锁：

```objc
@synchronized(array) {
    [array addObject: obj];
}
```

我个人更喜欢显式的锁，这样做既可以使事情更清楚，`@synchronized` 的性能没那么好，原因如下图所示。但它（`@synchronized`）可以很方便，不管怎样都是一个有趣的实现方式。

## 原理

Swift 版本的 `@synchronized` 是一个函数。它接受一个对象和一个闭包，并使用持有的锁调用闭包：

```swift
func synchronized(obj: AnyObject, f: Void -> Void) {
    ...
}
```

问题是，如何将任意对象变成锁？

在一个理想的世界里（从实现这个函数的角度来看），每个对象都会为锁留出一些额外的空间。在这个额外的小空间里 `synchronized` 可以使用适当的 `lock` 和 `unlock` 方法。然而不存在这种额外空间的话，这可能是幸运的，因为它会使系统上每个对象的内存大小膨胀，以实现大多数对象永远不会遇到的特性。

另一种方法是使用将对象映射到锁的表。然后 `synchronized` 可以查找表中的锁，并在那里执行 `lock` 和 `unlock`。这种方法的问题是表本身需要保证线程安全，它要么需要自己的锁，要么需要某种特殊的无锁数据结构。为表单独设置一个锁要容易得多。

为了防止锁不断累积常驻，表需要跟踪锁的使用情况，并在不再需要锁的时候销毁或者复用锁。

## 实现

对于将对象映射到锁的表，`NSMapTable` 非常合适这个方案。它可以配置为使用使用原始对象地址作为键（key），并且它可以保存对键（key）和值（value）的弱引用，从而允许系统自动回收未被使用的锁。

```swift
let locksTable = NSMapTable.weakToWeakObjectsMapTable()
```

这些对象将是 `NSRecursiveLock` 的实例。因为它是一个类，所以它可以很好地与 `NSMapTable` 一起使用，而不是像 `pthread_mutex_t` 那样。`@synchronized` 提供递归语义，这也是一样的。

表本身也需要一个锁。自旋锁（spinlock）对这的表现很好，因为对表的访问是短暂的：

```swift
var locksTableLock = OS_SPINLOCK_INIT
```

有了这个表，我们就可以实现以下方法：

```swift
func synchronized(obj: AnyObject, f: Void -> Void) {
```

它所做的第一件事就是在 `locksTable` 中找出与 `obj` 对应的锁，这必须使用 `locksTableLock` 进行：

```swift
OSSpinLockLock(&locksTableLock)
var lock = locksTable.objectForKey(obj) as! NSRecursiveLock?
```

如果表中没有任何对应锁，则创建一个新锁并进行设置：

```swift
if lock == nil {
    lock = NSRecursiveLock()
    locksTable.setObject(lock!, forKey: obj)
}
```

有了锁之后主表锁就可以释放了。为了避免死锁这必须要在调用 `f` 之前完成：

```swift
OSSpinLockUnlock(&locksTableLock)
```

现在我们可以调用 `f` 了，在调用的前后分别进行加锁和解锁操作：

```swift
    lock!.lock()
    f()
    lock!.unlock()
}
```

## 对比苹果的方案

苹果实现 `@synchronized` 的方案可以在 Objective-C runtime 源码中找到:

http://www.opensource.apple.com/source/objc4/objc4-646/runtime/objc-sync.mm

它的实现是为了性能而不是像上面的玩具实现那样简单。有趣的是可以看看它们之间有什么异同。

基本概念是相同的。存在一个全局表，它将对象指针映射到锁，然后该锁在 `@synchronized` 代码块前后加锁解锁。

对于底层的锁对象，Apple 使用配置为递归锁的 `pthread_mutex_t`，由于 `NSRecursiveLock` 可能都是使用 `pthread_mutex_t` 来实现的，因此这就省去了中间环节，并避免了运行时对 Foundation 的依赖。

表本身的实现为一个链表而不是一个哈希表。由于常见的情况是在任何给定的时间里只存在少数几个锁，所以这仍有良好的性能表现，并且可能比哈希表性能更好。每个线程缓存保存了最近在当前线程查找的锁，从而进一步提高性能。

存在着16个表保存在一个数组中，而不是单个全局表。对象根据其地址映射到不同的表。这减少了对不同对对象 `@synchronized` 操作之间不必要的资源竞争，因为它们可能使用不同的全局表。

苹果的实现没有使用弱指针引用（这会增加大量额外开销），而是为每个锁保留一个内部的引用计数。当引用计数达到零时，该锁可以给新对象重新使用。未使用的锁不会被销毁，但复用意味着在任何给定的时间内锁的总数限制为活动锁的最大数量，而不是随着新对象的使用而无限制增长。

苹果的实现方案是智能并高性能的，但与使用单独的显式锁相比，它仍然会带来一些不可避免的额外开销。尤其是：

1. 如果不相关的对象刚好被分配到同一个全局表中，那么它们仍然可能存在资源竞争。
2. 通常情况下在线程缓存中查找一个不存在的锁时，必须获取并释放一个自旋锁。
3. 必须做更多的工作来查找全局表中对象的锁。
4. 即使不需要，每个加锁/解锁周期都会产生递归语义方面的开销。

## 讨论

`@synchronized` 是一个有趣的语言结构，有一些实现方面的挑战。从根本上来说，它提供了线程安全，但实现本身需要同步安全。在幕后使用全局锁来保护对锁表的访问解决了这个困境。苹果的聪明实现保证了其高性能的表现。

**Comment by Yousanflics** [comment]
麻烦MM补充一下这篇文章的发布日期类型等等这些信息 Thx

**Comment by numbbbbb** [comment]
二次校对完成，有几处翻译错误。补上了文章开头的数据，可能需要CMB确定一下格式和内容是否正确。
