### ISSUE TITLE
【长】Friday Q&A 2015-02-06: Locks, Thread Safety, and Swift

### ISSUE THREAD

**Issue by saitjr** [SwiftGGTeam/translation#33]
https://www.mikeash.com/pyblog/friday-qa-2015-02-06-locks-thread-safety-and-swift.html

**Comment by lefex** [comment]
# Swift 中的锁和线程安全

在 Swift 中有个趣的现象，它没有与线程相关的语法，甚至明确的互斥锁/锁（mutexes/locks）。但是 Objective-C 中有 @synchronized 和原子属性。幸运的是，强大的平台 API 可以非常容易地应用到 Swift 中。今天，我要探讨这些 API 的使用和 Objective-C 的过度，主要的灵感来源于 Cameron Pulsford。

## 快速回顾一下锁

锁（lock）或者互斥锁（mutex）是一种结构，用来保证一段代码在同一时刻只有一个线程执行。它们通常被用来保证多线程访问同一可变数据结构时的数据一致性。主要有下面几种锁：

- 阻塞锁（Blocking locks）会一只等待锁直到被其他线程释放，这是一种常见的表现形式；
- 自旋锁（Spinlocks）使用一个循环不断地检查锁是否被释放。如果等待很少，这种锁非常高效，但是如果等待的情况非常多，则会浪费CPU时间；
- 读写锁（Reader/writer locks）允许多个读线程同时进入一段代码，但当写线程获取锁时，其他线程（包括读取器）只能等待。这可能是有用的，因为大多数数据结构读取时是线程安全的，当其他线程边读边写时是不安全的；
- 递归锁（Recursive locks）允许单个线程多次获取相同的锁。非递归锁被同一线程重复获取时可能会导致死锁、崩溃或其他错误行为。

## APIs

苹果提供了一系列不同的锁 API，下面是一个锁的列表： 

```
pthread_mutex_t.
pthread_rwlock_t.
dispatch_queue_t.
NSOperationQueue 当配置为 serial 时.
NSLock.
OSSpinLock.
```

除此之外，Objective-C 提供了 @synchronized 语法结构，它目前是基于 `pthread_mutex_t` 上的封装。与其他API不同的是，@synchronized 并未使用明确的锁对象，而是将任意 Objective-C 对象视为锁。@synchronized(someObject) 区域将阻止其他 @synchronized(someObject) 区域访问同一对象指针。这些不同的API有不同的行为和能力： 

- `pthread_mutex_t` 是一个可选择性地配置为递归锁的阻塞锁；
- `pthread_rwlock_t` 是一个阻塞读写锁；
- `dispatch_queue_t` 可以用作阻塞锁，也可以通过使用 barrier block 配置一个同步队列作为读写锁，还支持异步执行加锁代码；
- `NSOperationQueue`可以用作阻塞锁。与`dispatch_queue_t`一样，支持异步执行加锁代码。
- `NSLock` 是 Objective-C 类的阻塞锁，它的同伴类 `NSRecursiveLock` 是递归锁，顾名思义。
- `OSSpinLock` 是一个自旋锁，顾名思义。

最后，@synchronized 是一个阻塞递归锁。

### 值类型

注意，`pthread_mutex_t`, `pthread_rwlock_t`和 `OSSpinLock` 是值类型，而不是引用类型。这意味着如果你使用 `=` 操作它们，你就复制一个副本。这很重要，因为这些类型是无法复制的！如果复制了它们中的任意一个，拷贝将不可用，并且可能在尝试使用时崩溃。这些类型的 pthread 函数假定它们的内存地址与初始的时候一样，之后将它们移动到其他地方是一个坏主意。`OSSpinLock ` 不会崩溃，但你得到一个完全独立的锁，这不是你想要的。

如果使用这些类型，则必须小心，不要复制它们，无论是显式的使用 `=` 操作符，还是隐式地，例如，将它们嵌入到结构中或在闭包中捕获它们。

另外，由于锁本质上是可变对象，这意味着需要用var来声明它们。

其他锁都是是引用类型，意味着它们可以随意传递，并且可以用 let 声明。 

### 初始化

2015-02-10更新：本节中所描述的问题已经以惊人的速度被淘汰。苹果昨天发布了Xcode 6.3b1，其中包括 Swift 1.2。在其他更改中，现在使用一个空的初始化器导入C结构，将所有字段设置为零。简而言之，您现在可以编写`pthread_mutex_t()`，而不需要下面提到的扩展。

pthread 类型很难在 swift 中使用。它们被定义为不透明的结构体中包含了一堆存储变量，例如：

```
struct _opaque_pthread_mutex_t {
    long __sig;
    char __opaque[__PTHREAD_MUTEX_SIZE__];
};
```

目的是声明它们，然后使用 init 函数对它们进行初始化，使用一个指针存储和填充。在C中，它看起来像： 

```
pthread_mutex_t mutex;
pthread_mutex_init(&mutex, NULL);
```

这段代码可以正常的工作，只要你记得调用 `pthread_mutex_init`。然而，Swift真的真的不喜欢未初始化的变量。与上面代码等效的 swift 版本无法编译： 

```
var mutex: pthread_mutex_t
pthread_mutex_init(&mutex, nil)
// error: address of variable 'mutex' taken before it is initialized
```

Swift需要变量在使用前初始化。`pthread_mutex_init` 不使用传入的变量的值，只是重写它，但是Swift 不知道，因此它产生了一个错误。为了满足编译器，变量需要用某种东西初始化。在类型之后使用（），但任然报错：

```
var mutex = pthread_mutex_t()
// error: missing argument for parameter '__sig' in call
```

swift 需要那些不透明字段的值。`__sig` 可以传人零。`__opaque`有点烦人。下面的结构体需要桥接到 swift 中：

```
struct _opaque_pthread_mutex_t {
   var __sig: Int
   var __opaque: (Int8, Int8, Int8, Int8,
               Int8, Int8, Int8, Int8,
               Int8, Int8, Int8, Int8,
               Int8, Int8, Int8, Int8,
               Int8, Int8, Int8, Int8,
               Int8, Int8, Int8, Int8,
               Int8, Int8, Int8, Int8,
               Int8, Int8, Int8, Int8,
               Int8, Int8, Int8, Int8,
               Int8, Int8, Int8, Int8,
               Int8, Int8, Int8, Int8,
               Int8, Int8, Int8, Int8,
               Int8, Int8, Int8, Int8,
               Int8, Int8, Int8, Int8)
}
```

没有一个简单的方法使用一堆 0 构建一个元组，只能像下面这样把所有的0都写出来：

```
var mutex = pthread_mutex_t(__sig: 0,
                             __opaque: (0, 0, 0, 0, 0, 0, 0, 0,
                                        0, 0, 0, 0, 0, 0, 0, 0,
                                        0, 0, 0, 0, 0, 0, 0, 0,
                                        0, 0, 0, 0, 0, 0, 0, 0,
                                        0, 0, 0, 0, 0, 0, 0, 0,
                                        0, 0, 0, 0, 0, 0, 0, 0,
                                        0, 0, 0, 0, 0, 0, 0, 0))
```

这太糟糕了，但我找不到一个好办法。我能想到最好的做法就是把它包在一个扩展中，这样空的（）就可以工作了。以下是我做的两个扩展： 

```
    extension pthread_mutex_t {
        init() {
            __sig = 0
            __opaque = (0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0)
        }
    }

    extension pthread_rwlock_t {
        init() {
            __sig = 0
            __opaque = (0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0,
                        0, 0, 0, 0, 0, 0, 0, 0)
        }
    }
```

可以通过下面这种方式使用：

```
var mutex = pthread_mutex_t()
pthread_mutex_init(&mutex, nil)
```

## 锁的封装

为了使这些不同的API更易于使用，我编写了一系列小型函数。我决定把 `with` 作为一个方便、简短、看起来像语法的名字，灵感来自 python 的 `with` 声明。Swift 函数重载允许不同类型使用相同的名称。基本形式如下所示：

```
func with(lock: SomeLockType, f: Void -> Void) { ...
```

然后在锁定的情况下执行函数 f。让我们实现这些类型。

对于值类型，它需要一个指向锁的指针，以便 lock/unlock 函数可以修改它。这个实现`pthread_mutex_t` 只是调用相应的 lock 和 unlock 函数，f 函数在两者之间调用：

```
func with(mutex: UnsafeMutablePointer<pthread_mutex_t>, f: Void -> Void) {
    pthread_mutex_lock(mutex)
    f()
    pthread_mutex_unlock(mutex)
}
```

`pthread_rwlock_t` 的实现几乎完全相同：

```
func with(rwlock: UnsafeMutablePointer<pthread_rwlock_t>, f: Void -> Void) {
    pthread_rwlock_rdlock(rwlock)
    f()
    pthread_rwlock_unlock(rwlock)
}
```

与读写锁做了个对比，它们看起来很像：

```
func with_write(rwlock: UnsafeMutablePointer<pthread_rwlock_t>, f: Void -> Void) {
    pthread_rwlock_wrlock(rwlock)
    f()
    pthread_rwlock_unlock(rwlock)
}
```

一个 `dispatch_queue_t` 更简单。它只是对 `dispatch_sync：` 的封装：

```
func with(queue: dispatch_queue_t, f: Void -> Void) {
    dispatch_sync(queue, f)
}
```

事实上，如果一个人为自以为非常聪明并且想要迷惑人们，那么可以利用 Swift 的功能性，并简单地写出：

`let with = dispatch_sync`

由于几个原因，这是不明智的，其中最重要的是它与我们这里使用的基于类型的重载混淆。

`NSOperationQueue` 在概念上是相似的，但没有直接的等同物 `dispatch_sync`。相反，我们创建一个操作(operation)，将其添加到队列中，并明确地等待它完成：

```
func with(opQ: NSOperationQueue, f: Void -> Void) {
    let op = NSBlockOperation(f)
    opQ.addOperation(op)
    op.waitUntilFinished()
}
```

实现 `NSLock` 看起来像 `pthread` 版本，只是锁定调用有稍微不同：

```
func with(lock: NSLock, f: Void -> Void) {
    lock.lock()
    f()
    lock.unlock()
}
```

最后，`OSSpinLock` 实现同样也是如此：

```
func with(spinlock: UnsafeMutablePointer<OSSpinLock>, f: Void -> Void) {
    OSSpinLockLock(spinlock)
    f()
    OSSpinLockUnlock(spinlock)
}
```

### 模仿@synchronized

使用上面的封装，模仿 `@synchronized` 的实现很简单。添加一个属性到你的类中，并持有一个锁，然后使用 `with` 替代你以前使用 `@synchronized` 的位置：

```
let queue = dispatch_queue_create("com.example.myqueue", nil)

func setEntryForKey(key: Key, entry: Entry) {
    with(queue) {
        entries[key] = entry
    }
}
```

令人遗憾的是，从块中获取数据不那么令人愉快。`@synchronized` 可以让你从内部 `return`，但是 `with` 做不到。你必须使用一个 `var` 变量在 block 内部赋值给它：

```
func entryForKey(key: Key) -> Entry? {
    var result: Entry?
    with(queue) {
        result = entries[key]
    }
    return result
}
```

应该可以将样板代码封装在一个通用函数中，但是它很难得到 Swift 编译器的类型推断，并且还没有解决方案。

### 模仿原子属性

原子属性并不常用。问题是，与许多其他有用的代码属性不同，原子性并不安全。例如，如果函数f不存在内存泄漏，函数g不存在内存泄漏，那么函数h只是调用f和g也不会存在内存泄漏。原子性也是如此。举一个例子，假设你有一组原子，线程安全的Account类：

```
let checkingAccount = Account(amount: 100)
let savingsAccount = Account(amount: 0)
```

现在你把钱转到储蓄中：

```
checkingAccount.withDraw(100)
savingsAccount.deposit(100)
```

在另一个线程中，总计余额并告诉用户：

```
println("Your total balance is: \(checkingAccount.amount + savingsAccount.amount)")
```

如果这只是在错误的时间运行，它将打印零而不是100，尽管事实上这些Account对象本身是完全原子的，并且用户总是有100的余额。因此，将整个子系统构建为原子通常更好，而不是单个属性。

在极少数情况下，原子属性是有用的，因为它是一个独立的东西，只需要线程安全。要在Swift中实现这一点，需要一个计算属性来完成锁定，而第二个常规属性实际上会保存该值：

```
private let queue = dispatch_queue_create("...", nil)
private var _myPropertyStorage: SomeType

var myProperty: SomeType {
    get {
        var result: SomeType?
        with(queue) {
            result = _myPropertyStorage
        }
        return result!
    }
    set {
        with(queue) {
            _myPropertyStorage = newValue
        }
    }
}
```

### 选择你的锁API

`pthread APIs` 由于在 Swift 中使用起来非常难，所以它的优势立刻削减了很多。我经常喜欢在 C 和 Objective-C 中使用它们，因为它们相当直接且快速，但除非真正需要它，否则这不值得。

读写锁大多数不值得的关心。大多数情况下，读写速度非常快，读写锁使用的额外开销超过了具有多个并发读取器的能力。

递归锁会发生死锁。多数情况下它们是有用的，但如果你发现自己采用了这样一个设计：你需要获取一个已经在当前线程被锁住的锁。你需要重新考虑设计它，因为通常来说，这是不需要的。

我的意见是，如果有疑问，默认使用 `dispatch_queue_t`。他们更重量级，但不会产生太多问题。该API非常方便，并且确保你永远不会忘记调用 lock 和 unlock。它提供了许多可以派上用场的 API，如使用单个 `dispatch_async` 在后台执行被锁定的代码，或者设置定时器或其他作用于 queue 的事件源，以便它们自动执行锁定。你甚至可以使用它作为 `NSNotificationCenter` 观察者和通过使用`NSOperationQueue` 的属性 `underlyingQueue` 作为`NSURLSession` 代理。

`NSOperationQueue` 希望它可以如同 `dispatch_queue_t` 一样酷，很少有理由使用它作为锁定API。使用起来比较麻烦，并且没有提供任何作为锁定API的典型用途，尽管操作自动依赖关系管理在其他情况下有时可能有用。

`NSLock` 是一个简单的锁定类，易于使用和合理快速。如果由于某种原因需要锁定和解锁调用，而不是基于`dispatch_queue_t` 块的API，那么这是一个不错的选择，但在大多数情况下没有什么理由使用它。

`OSSpinLock` 对于经常使用锁定，竞争较少且锁定代码运行速度快的用户来说，这是一个很好的选择。它的开销非常少，这有助于提升执行成功路径时的性能。另一方面，对于代码可能会在很长一段时间内保持锁定或竞争很常见而言，这是一个糟糕的选择，因为这会浪费CPU时间。通常，默认为`dispatch_queue_t`，`OSSpinLock` 如果它开始显示在探查器（profiler）中，请记住它相当容易优化。

### 总结

Swift 中并没有用于线程同步的语言支持，但是这个缺点不仅仅是为了满足 Apple 框架中丰富的关于锁的API。GCD 和 `dispatch_queue_t` 仍然是杰作，并且该 API 在 Swift 中非常出色。我们没有`@synchronized` 或原子性质，但我们有更好的东西。

**Comment by liberalisman** [comment]
原文：
> An interesting aspect of Swift is that there's nothing in the language related to threading, and more specifically to mutexes/locks. Even Objective-C has @synchronized and atomic properties
原翻译：
> 在 Swift 中有个趣的现象，它没有与线程相关的语法，甚至明确的互斥锁/锁（mutexes/locks）。但是 Objective-C 中有 @synchronized 和原子属性
建议：
> 在 Swift 中有个趣的现象，它没有与线程相关的语法，甚至明确的互斥锁/锁（mutexes/locks）。甚至连 Objective-C 中有 @synchronized 和原子属性也没有。

**Comment by liberalisman** [comment]
It may be possible to roll the call to pthread_mutex_init into the extension initializer as well, but there's no guarantee that self in a struct init points to the variable being initialized. Since these values can't be moved in memory after being initialized, I wanted to keep the initialization as a separate call.

这一段在翻译过程中被遗漏了

**Comment by Yousanflics** [comment]
因为考虑到下周要发文章了所以今天定稿一下 发现翻译里面的问题还是不少的 主要还是翻译生硬的问题@liberalisman说的几点我直接在原文里面修改了感觉会让读者更舒服一点，并且感谢liber的错别字修改 很仔细 棒喔 还有帮主的参考@numbbbbb，最后说一下重点的问题，因为几天要check的文章有点多所以修改记录没有像liber那样写下来不过应该看git的记录应该可以看出来吧？非常重要的问题是在翻译过程中有语意根本上的差别一句话翻译成中文来直接给换了个意思这个我觉得不是多读几遍的问题还是英语能力的问题希望楼主有空可以多看看英文原著提升一下能力（现在记得比较清楚的是functional nature那一句 直接整句话的后半部分意思给改写了）下次加油💪

**Comment by liberalisman** [comment]
根据 @Yousanflics  的建议，刚刚做了大量的修改，主要是为了解决文中语义不通畅的地方，做了适量的删减，同时改了一部分格式。

**Comment by lefex** [comment]
@numbbbbb @liberalisman @Yousanflics 非常感谢你们，我会在后续的翻译中多注意。
