### ISSUE TITLE
Friday Q&A 2015-01-23: Let's Build Swift Notifications

### ISSUE THREAD

**Issue by saitjr** [SwiftGGTeam/translation#35]
https://www.mikeash.com/pyblog/friday-qa-2015-01-23-lets-build-swift-notifications.html

**Comment by liberalisman** [comment]
# 让我们来构建Swift通知

`NotificationCenter` 是一个非常有用的API，它在苹果系统框架中无处不在， 并常在我们的代码中看到它的身影。我曾在[这篇文章](https://www.mikeash.com/pyblog/friday-qa-2011-07-08-lets-build-nsnotificationcenter.html)中尝试构建 Objective-C 版本的 `NotificationCenter`。 这次， 我想用 Swift 来构建，但我并不是简单的将其翻译成 Swift，相反，我将构建新的 API 并结合 Swift 语言特性并使其更快，更好，更强大。

**NSNotifications**

`NSNotification` 既简单又强大，这就是它在各种框架中频繁出现的原因。具体来说，它有如下几个明显的优势:

1. 通知的发送者和接收者之间松耦合的。
2. 支持一个通知多个接受者。
3. 支持通过 `userInfo` 属性来自定义数据内容。

同时它也有一些明显缺点:

1. 通知的发送及注册使用的是系统提供的单例对象，与你的类没有明确的关系。
2. 对某个特定类来说， 通知的可用性并不是很清楚。
3. 对于使用userInfo的通知,，里面的键的具体的类型并不是十分清楚。
4. `userInfo`的键类型只要遵循 AnyHashable 即可，接受者接收到数据后， 无法明确知道发送者发送的具体类型，同时非对象类型的属性装箱/解包很麻烦。
5. 移除对指定通知观察需要显示调用。
6. 对于任一给定的通知, 很难检测出哪些对象注册为观察者，这使得调试起来很困难。

在接下来的Swift构建中，我将解决这些问题。

**API 概述**

API的核心在于一个叫ObserverSet的类, 这个类的实例对象持有一个观察者的集合, 这个集合里的观察者对于某个指定对象发送的某个指定通知感兴趣。相对于声明各种字符串常量以及使用单例作为媒介，通知在该类中仅仅作为一个实例属性:

```swift
 class ExampleNotificationSender {
        public let exampleObservers = ObserverSet<Void>()
 }
```

`Void` 是与通知一起发送的数据类型，它表示通知没有任何附加数据。发送指定类型数据也是非常的简单：

```swift
public let newURLObservers  =  ObserverSet<NSURL>()
```
当这个通知被发送时，都会向观察者传递一个 `NSURL` 类型的数据。

你也可以使用元组来将不同数据类型的数据结合到一起:

```swift
public let newItemObservers = ObserverSet<(String, Int)>()
```

这种方式为会为观察者提供一个名字和索引。 如果你想更加清晰明了，你甚至可以添加对应的参数名称。

```swift
public let newItemObservers = ObserverSet<(name: String, index: Int)>()
```

利用 `add` 方法注册一个通知, 它会有一个回调给调用者;

```swift
object.exampleObservers.add { println("Got an example notification") }
object.newURLObservers.add { println("Got a new URL: \($0)") }
```
该 `add` 方法会返回一个可用于移除观察者令牌(Token):

```swift
let token = object.newItemObservers.add{ println("Got a new item named \($0) at index \($1)") }
...
object.newItemObservers.remove(token)
```

常见的情况是传递进去的参数为一个方法，并注册为观察者的对象被销毁后， 需要移除不在接收通知。利用提供的 `add` 方法是也很容易实现:

```swift
object.newItemObservers.add(self, self.dynamicType.gotNewItem)

func gotNewItem(name: String, index: Int) {
    println("Got a new item: \(name) \(index)")
}
```

`self.dynamicType` 的语法看起来有一点点冗长但可接受。 观察者的集合将会弱引用 `self` 并在其被销毁的时候自动移除该对象，同时它会在触发通知时调用`gotNewItem`。

发送通知也很简单，你仅仅需要调用 `notify` 方法并传递合适的参数:

```swift
exampleObservers.notify()
newURLObservers.notify(newURL)
newItemObservers.notify(name: newItemName, index: newItemIndex)
```

这样设计的 API 很好的解决了系统原生通知存在的问题:

1. 没有涉及到单例对象，每一个通知的观察者都用一个独立的观察者集合实例表示。
2. 对于指定的对象来说，它观察的通知都是显示作为它的属性存在的。
3. 通知传递给观察者的参数类型是显示指定的。观察者接收到通知后，可以很明确知道数据是类型。
4. 通知传递的参数类型是显示指定，通知的发送者与接受者之间的参数类型检查由编译器来检查， 并且参数支持所有的数据类型， 不需要装箱操作。
5. 当观察者被销毁后， 观察者身份自动解除。
6. 每个观察者集合都持有一列入口, 这些入口可以在debugger中进行调试。

看起来不错！那么，我们如何构建它？


**观察者函数类型(Observer Function Types)**

我们假设传递给观察者的参数称为 `Parameters`，这也将作为泛型参数的名称。本质来说， 观察者函数类型是 `Parameters -> Void`。然而常见的情况是观察者函数是一个方法，它的内部可能会强引用观察者对象， 这使得弱引用观察者对象并在其销毁的时候移出观察者集合变得很困难。当你从类中获取某个方法时， 例如 `self.dynamicType.gotNewItem`，这个方法的实际类型是 `TheClass -> Parameters -> Void`，你调用这个方法并传给它一个该类的实例对象，然后它将为适用于该实例的方法返回一个新函数。

为了更好的组织代码，我们将存储观察者，并弱引用它们，同时我们也会存储观察者函数。`add` 方法的有一种更简单的形式，它可以简单地包装在另一个抛出其参数并返回原始函数的函数中。由于观察者对象可以是不同的类型，因此我们将它们存储为 `AnyObject` 并将观察者函数声明为 `AnyObject -> Parameters -> Void`。

**代码**

你可以在 Github 上面查看具体代码的实现, 链接:[https://github.com/mikeash/SwiftObserverSet](https://github.com/mikeash/SwiftObserverSet)

**实体(Entries)**

观察者集合里面每个实体都弱引用观察者以及保存着观察者接收到通知后执行的函数。这个小的泛型类将这二者绑定在一起。

```swift

public class ObserverSetEntry<Parameters> {
    private weak var object: AnyObject?
    private let f: AnyObject -> Parameters -> Void

    private init(object: AnyObject, f: AnyObject -> Parameters -> Void) {
        self.object = object
        self.f = f
    }
}
```

观察者的集合可以检查 `object` 对象并且执行对应的方法。 当弱引用的观察者对象被销毁置为 nil 的时候, 移出观察者的集合。该类被标记为 `public` 是因为它会返回给调用者作为`remove`方法的参数

理想情况下, 这个类应该嵌套在 `ObserverSet` 里面。然而，Swift 不允许泛型嵌套, 因此它必须是一个单独的类型。

**观察者集合(Observer Set)**

`ObserverSet` 同样也有一个泛型的参数:

```swift
public class ObserverSet<Parameters> {}
```
`NSNotificationCenter` 是线程安全的, 这个类应该也是这样。我所采用的策略是使用串行队列来实现:

```swift
private var queue = dispatch_queue_create("com.mikeash.ObserverSet", nil)
```

我也为它写了一个辅助函数：

```swift
private func synchronized(f：Void -> Void) { 
    dispatch_sync(queue, f）
}

```

这样, 使用共享数据就像在代码中写 `synchronized{ ...code... }` 一样简单。

这些实体对象保存在一个数组里面:

```swift
private var entries: [ObserverSetEntry<Parameters>] = []
```

确切来说，这应该是个集合而不是个数组。 然而 Swift 中的集合并不是那么的好用，因为它没有内置的集合的类型。 相反，你要么使用 `NSSet`, 要么使用一个空值的字典类型。 因为观察者集合同时包含数目是有限的, 为了清晰明了，我采用数组来设计。

Swift 要求使用一个公开的构造函数方法, 尽管它是空的, 默认的函数显然是不公开的。

```swift
public init() {}
```

现在需要进行相关配置，我们来构建一个 `add` 方法, 它接收一个观察者的对象以及对应执行的函数.

```swift

public func add<T: AnyObject>(object: T, _ f: T -> Parameters -> Void) -> ObserverSetEntry<Parameters> {}

```

下一步构建一个实体对象,  `ObserverSetEntry`期望一个为`AnyObject`的参数, 而 `f` 为 `T` 类型, 显然不一样。 设计一个小型的适配器用于处理类型转换不一致的问题:

```swift
let entry = ObserverSetEntry<Parameters>(object：object, f:{ f($0 as T)}）
```

通过这种方式转换是有点别扭，但是它的确能达到我们的预期。

当实体对象创建后就加入到数组里面:

```swift
synchronized {
    self.entries.append(entry)
}
```

最后返回实体对象给对应的调用者:

```swift
return entry
```

另一个 `add` 方法也有一个小型的适配器:

```swift
public func add(f: Parameters -> Void) -> ObserverSetEntry<Parameters> {
    return self.add(self, { ignored in f })
}
```
这里简单的将 `self` 作为对象传递过去，它能保证对象一直存在，永不被移出集合。因为当对象被销毁置为nil的时候, 观察者就会被移除集合。函数传递的第二个参数只是忽略其参数并返回f

remove方法通过过滤数组来移除符合条件的元素。 Swift 数组类型没有任何直接删除的方法, 但是可以通过 `filter`方法 来实现。

```swift
public func remove(entry: ObserverSetEntry<Parameters>) {
    synchronized {
        self.entries = self.entries.filter{ $0 !== entry }
    }
}
```

`notify` 方法的原理很简单就是: 遍历对象, 调用对应的方法，同时需要删除已被销毁的对象。 然而当你同步访问这些观察者对象并调用这其方法，这样很容易造成死锁。 为了避免这些问题，我将新建一个临时的数组来保存所有的非空的观察者所执行的函数， 然后迭代这个数组。 完整的功能如下:


```swift
public func notify(parameters: Parameters) {
```

声明一个保存被调用的函数数组

```swift

var toCall: [Parameters -> Void] = []

```

在离开 `synchronized `回调的作用域之前,我们通过 ` Filter ` 函数清理里面为 nil 的元素;

```swit
     self.entries = self.entries.filter{ $0.object != nil }
    }
```

现在相关的函数已经被保存起来了, `synchronized` 代码块功能已经调用完成， 现在来调用执行对应的函数:

```swift
for f in toCall {
    f(parameters)
}
```

这就是一个完整的 `ObserverSet` 类, 别忘记最后的大括号:

```swift
}
```

**元组注记:**

您会注意到，所提供的ObserverSet代码都不涉及有多个参数的情况，例如：

```swift
public let newItemObservers = ObserverSet<(String, Int)>()
```

然而, 上面的代码确能够正常的运行, 这是怎么回事呢？

事实上，Swift在 带有多个参数的函数和一个带有一个元组的类型为参数的函数之间没有区别。例如，下面代码使用两种方式调用函数：

```swift
func f(x: Int, y: Int) {}

f(0, 0)

let params = (0, 0)
f(params)
```

这意味着ObserverSet代码可以为具有一个参数的函数编写，并且可以直接获得对多个参数的支持。在某些情况下, 这样做会有很大的限制(例如: 你无法需改参数)， 但是在我们的场景中表现很不错。



**结束语**

`NSNotificationCenter` 使用起来非常的方便。 Swift 语言特性能使其更加的便捷。 泛型构建的简单API来适应类似相同的情况, 并提供静态的类型以及对应的静态类型检查。

这就是今天所有的内容, 下次再回来进行更振奋人心的尝试。与此同时，星期五问答是由读者的想法驱动的，所以如果你有一些你想看到的东西，请发送邮件到: mike@mikeash.com
