### ISSUE TITLE
Core ML for iOS Apps in iOS 11

### ISSUE THREAD

**Issue by mmoaay** [SwiftGGTeam/translation#39]
[http://jamesonquave.com/blog/core-ml-for-ios-apps-in-ios-11/](http://jamesonquave.com/blog/core-ml-for-ios-apps-in-ios-11/)

**Comment by Yohann-Chen** [comment]
原文链接=http://jamesonquave.com/blog/core-ml-for-ios-apps-in-ios-11/
作者=Jameson Quave
原文日期=2017/06/05
译者=Yohann Chen
校对= 
定稿= 
发布时间= 

在WWDC 2017上宣布的Core ML是一套由Apple构建的用于iOS 11或更高版本设备的新API。通过Core ML，开发人员可以将机器学习模型整合到他们的移动应用程序中，并使用Metal API加速推理。这意味着模型的处理将比使用其他系统（如TensorFlow或Caffe2）快得多。

值得注意的是，在WWDC主题演讲中，有人提到Core ML将支持来自Keras或Caffe的模型。可以将许多现有模型转换在设备上更快的加速工作。

核心ML支持以下主要特性：

- 深度神经网络
- 递归神经网络
- 卷积神经网络
- 支持向量机
- 树集成
- 线性模型

这全部通过设备上的处理完成，并支持iOS，macOS，watchOS和tvOS。

Core ML旗下是Model Converter(模型转换器)，Natural Language API(自然语言API)和Vision API。(视觉API)

一旦API公开，我将在这里收集关于官方Core ML文档的参考资料。跟随我，让我们开始学习吧！

目前，我们知道API将支持人脸跟踪，人脸检测，地标检测，文本检测，矩形检测，条码检测，对象跟踪和图像配准。

**Comment by liberalisman** [comment]
1.中英文在衔接处请加空格。
2.英文专属名词，例如 `Core ML`,可以加上单引号，着重显示。
3.原文：这意味着模型的处理将比使用其他系统（如TensorFlow或Caffe2）快得多。
   建议：这意味着模型的处理速度将比 TensorFlow 或 Caffe2 等其他系统要快得多。
4.原文：可以将许多现有模型转换在设备上更快的加速工作。
   建议：可以将许多现有模型在新的加速器下转化到设备上工作。
