### ISSUE TITLE
Building Swift 3.0 on an ARMv7 System 

### ISSUE THREAD

**Issue by saitjr** [SwiftGGTeam/translation#40]
https://dev.iachieved.it/iachievedit/building-swift-3-0-on-an-armv7-system/

**Comment by Pancf** [comment]
在ARMv7系统上构建Swift3.0

作者注：这篇文章取代了我们为BeagleBone Black (译者注：这是一款由德州仪器与Digi-Key和Newark element14合作生产的低能耗开源的单板机) 和Raspberry Pi 3 (树莓派) 构建Swift 3.0的其他文章，因为它利用了Swift ARM组织的仓库。



为了在一个ARMv7系统上构建原生Swift 3.0，你将需要以下东西：

- 一个适合并且强大的ARMv7系统；我们使用BeagleBoard X15 设备构建总共花了大约4小时，在Raspberry Pi 3 上花了6小时
- 基于USB3闪存驱动或者UHS-I/class 10 microSD卡的高速IO设备，容量需要至少16GB (我喜欢Patriot EP 系列，因为它的性价比和相对较高的写入速度)
- 一个兼容的Ubuntu的发行版本，例如Ubuntu Xenial 16.04]
- 耐心

安装构建所需要的依赖

编译Swift需要一些依赖。在终端输入以下命令：

    # sudo apt-get install -y git cmake ninja-build clang uuid-dev libicu-dev icu-devtools libbsd-dev libedit-dev libxml2-dev libsqlite3-dev swig libpython-dev libncurses5-dev pkg-config autoconf libtool systemtap-sdt-dev libcurl4-openssl-dev

增加一些内存

在ARMv7系统上构建Swift你将需要至少2G的内存。如果你使用的是树莓派3，你可能会想在自带的1G内存基础上翻倍。

    # cd /var/cache
    # sudo mkdir swap
    # cd swap
    # sudo fallocate -l 1G 1G.swap
    # sudo mkswap 1G.swap
    Setting up swapspace version 1, size = 1024 MiB (1073737728 bytes)
    no label, UUID=184d002a-2f15-4b23-8360-8e792badc6a2
    # sudo chmod 600 1G.swap
    # sudo swapon 1G.swap

使用build-swift

build-swift是我们的Github仓库，仓库中有几个帮助脚本可以简化我们在ARM上构建Swift的过程。

    # git clone https://github.com/swift-arm/build-swift
    # cd build-swift

默认情况下，build-swift会切换到swift-3.0分支。

仓库内含的脚本 (在scripts目录内)都很简单：

- get.sh - 下载所有构件Swift需要的仓库；这些仓库来自Swift ARM 组织，已经专门为在ARMv7上构建打了补丁
- update.sh - 更新你本地的所有脚本，保证跟Github上最新的一致
- package.sh - 运行Swift的build-script脚本
- clean.sh - 删除构建工具
- distclean.sh - 删除构建工具和仓库

我建议你看看每个shell脚本，在运行前了解一下脚本的内在逻辑。它们非常简单，但值得你花时间去理解一下它们在做什么。

Let's Do This

请确认你已经：

- 安装了所有需要的依赖包
- 系统有足够的内存 (至少2G)
- 从Github上克隆了build-swift

现在，克隆所有需要的仓库

    # cd build-swift
    # ./scripts/get.sh

在一张高速SD卡上，大约需要15分钟来下载并写入所有内容。

然后，编译。Swift on ARM团队使用Jenkins 来运行构建工作，但是如果你使用nohup来确保在终端关闭后编译工作可以继续，你可以使用这条命令：

    # nohup ./scripts/package.sh > swiftbuild.log &

要观察构建过程中产生的输出，请使用tail -F swiftbuild.log。

现在，你只需要静候佳音。在 RaspBerry Pi 3上完整构建 Swift需要6小时以上。但等待是值得的，回报给你的是一个swift.tar.gz包，它可以在运行 Ubuntu Xenial的RaspBerry Pi 2或Pi 3上安装。我喜欢在 /opt/swift/目录安装Swift：

    # cd /opt
    # mkdir -p swift/swift-3.0
    # cd swift/swift-3.0
    # tar -xzvf /path/to/swift.tar.gz

然后你可以通过export PATH=/opt/swift/swift-3.0/usr/bin:$PATH来设置环境变量。为了可以使用swiftc和swift，你还需要运行下列命令：

    sudo apt-get install -y libicu-dev
    sudo apt-get install -y clang-3.6
    sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.6 100
    sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-3.6 100

获得帮助

如果你在编译过程中遇到了麻烦，请加入我们的swift-arm Slack。
