### ISSUE TITLE
【短】selector () and the responder chain

### ISSUE THREAD

**Issue by mmoaay** [SwiftGGTeam/translation#49]
[http://swiftandpainless.com/selector-and-the-responder-chain/](http://swiftandpainless.com/selector-and-the-responder-chain/)

**Comment by mmoaay** [comment]
# #selector() 和响应者链

由于 Swift 2.2 中 Selector 的新语法，我在 [“Utilize the responder chain for target action”](http://swiftandpainless.com/utilize-the-responder-chain-for-target-action/) 一文中使用的方法产生了一个警告，让我们来修复它吧。

## 协议实现

首先，我们添加一个协议：

```objc
@objc protocol DetailShowable {
  @objc func showDetail()
}
```

然后，我们可以像 [Andyy Hope]() 的[这篇神奇的博文](https://medium.com/swift-programming/swift-selector-syntax-sugar-81c8a8b10df3#.6gteb7p1s)中描述的那样，为 `Selector` 添加一个扩展，代码如下：

```objc
private extension Selector {
  static let showDetail = #selector(DetailShowable.showDetail)
}
```

将 action 添加到响应链就会像下面这段代码一样简单：

```objc
button.addTarget(nil,
                 action: .showDetail,
                 forControlEvents: .TouchUpInside)
```

接下来，在响应者链中的一些响应对象需要满足 `DetailShowable` 协议。

你可以在 [GitHub](https://github.com/dasdom/SelectorSyntaxSugar) 找到相关代码。

**Comment by chenmingbiao** [comment]
老文章，两年前已经翻译过
地址：http://swift.gg/2016/04/20/selector-and-the-responder-chain/
