### ISSUE TITLE
【中】Enums And Optionals

### ISSUE THREAD

**Issue by sfmDev** [SwiftGGTeam/translation#68]
http://khanlou.com/2018/04/enums-and-optionals/

**Comment by ennisk** [comment]
# Swift 的可选型枚举

去年我写了一篇关于[在类中添加普通可选型属性使扩展功能变得更简单](http://khanlou.com/2017/03/that-one-optional-property/)的文章，但是从长远来看会对代码库造成一定的损害，本文接上一篇内容。

假如你正在设计 APP 中的认证流程。你知道这个流程不会是简单或线性的，所以你想写一些可测试的代码。你的方法是首先考虑在所有流程的页面中添加枚举：

```
enum AuthFlowStep {
    case collectUsernameAndPassword
    case findFriends
    case uploadAvatar
}
```

然后，将所有复杂的逻辑放入到一个函数中，该函数接收当前步骤和当前状态，并输出流程中的下一个步骤。

```
func stepAfter(_ currentStep: AuthFlowStep, context: UserState) -> AuthFlowStep
```

这应该很容易测试，到目前为止一切都还好。

除此之外 — 你正在研究逻辑，并且你意识到有时候你不会总能返回一个 `AuthFlowStep` 。一旦用户提交了所有完全认证需要的数据，你需要一些信息来表示流程已经结束了。在函数中，你想要返回一个已经存在的类型的特例。你会怎么做呢？修改返回类型为可选的：

```
func stepAfter(_ currentStep: AuthFlowStep, context: UserState) -> AuthFlowStep?
```

这个解决方案有效，你可以在你的 [coordinator](http://khanlou.com/2015/10/coordinators-redux/) 调用这个函数，并以此开始工作：

```
func finished(flowStep: AuthFlowStep, state: UserState, from vc: SomeViewController) {
	let nextState = stepAfter(flowStep, context: state)
```

当我们得到 `nextState` ，由于这是可选的，所以默认在这里 `guard` 方法处理使其当成非可选值。

```
guard let nextState = stepAfter(flowStep, context: state) else {
  self.parentCoordinator.authFlowFinished(on: self)
}
  switch nextState {
  case .collectUsernameAndPassword:
		//build and present next view controller
```

这样一点奇怪的感觉，但是我想起 Swift 中 [Olivier 的模式匹配指南](http://alisoftware.github.io/swift/pattern-matching/2016/04/24/pattern-matching-3/#syntactic-sugar-on-optionals) ，且我可以在 `switch` 语句中同时处理可选值和枚举值：

```
func finished(flowStep: AuthFlowStep, state: UserState, from viewController: SomeViewController) {
	let nextState = stepAfter(flowStep, context: state) // Optional<AuthFlowStep>
	switch nextState {
	case nil:
		self.parentCoordinator.authFlowFinished(on: self)
	case .collectUsernameAndPassword?:
		//build and present next view controller
```

这个小问号让我匹配了一个枚举的可选情况。它有助于更好的编码，但仍让有些地方不太正确。如果我做了一个大转变，为什么我要打开一个嵌套的东西？`nil` 又意味着什么？

如果你关注这篇文章的标题，也许你已经知道了这是怎么回事。让我们来看看可选的定义。在底层，它就像 `AuthFlowState` 一样就是个枚举：

```
enum Optional<Wrapped> {
	case some(Wrapped)
	case none
}
```

当将枚举插入可选类型时，基本上只是向包内枚举添加一个实例。但是我们完全控制了我们的 `AuthFlowStep` 枚举！我们可以改变它，并直接添加新的案例。

```
enum AuthFlowStep {
    case collectUsernameAndPassword
    case findFriends
    case uploadAvatar
    case finished
}
```

现在我们可以从函数输出中删除 `?` 了。

```func stepAfter(_ currentStep: AuthFlowStep, context: UserState) -> AuthFlowStep```

我们的 `switch` 语句现在可以直接切换到所有的情况，对于 `nil` 情况没有特殊的处理。

为什么这样更好？原因有几个：

首先，现在 `nil` 被定义了。以前，使用该函数的用户可能不清楚函数返回 `nil` 意味着什么。他们要么去阅读文档求助，或者更糟糕的，阅读函数中的代码，去了解什么时候会返回 `nil` 。

第二，简单才是王道，不需要先用 `guard` 语句处理然后再用 `switch` 语句处理，或者 `swtich` 语句处理两层枚举，一层枚举总是容易被处理的。

最后，准确来说，保持 `renturn nil` 在函数运行的任何地方的有效性是退出函数的保障。下一个开发者可能发现自己处于一种想要退出函数的特殊情况，所以提前  `return nil` ， 这个时候 `nil` 出现了两个含义，无法正确处理任何一个。

当你把特殊情况添加到枚举中，也值得思考要使用什么名字。有很多可使用的名字，任何一个在上下文中可能都有含义：`.unknow`，`.none`，`.finished`，`.initial`，`.notFound`，`.default`，`.nothing`，`.unspecified` 等等（另外一点需要注意的是如果你有一个 `.none` 类型，且你确定这个值是可选的，那么无路你使用 `Option.none` 还是 `YourEnum.none` 都会引起歧义的）。

我使用的的是流程状态的常规例子，但我想这种模式也同样能适应到其他扩展的情况 — 当你有一个枚举且想要封装成一个可选类型的时候，从持续性方面考虑，你需要思考是否会有另一个枚举值处于隐藏状态。

感谢 [Bryan Irace](https://irace.me/) 的反馈和本文的例子
