### ISSUE TITLE
【中】Swift 4 Generics: How to Apply Them in Your Code and iOS Apps

### ISSUE THREAD

**Issue by BigNerdCoding** [SwiftGGTeam/translation#93]
https://appcoda.com/swift-generics/

**Comment by Desgard** [comment]
这一篇已有翻译组候选人试译，优先级降低领取

**Comment by liberalisman** [comment]
这篇目前有人已经翻译出来了，先将这个 I
ssue 关闭。

**Comment by BigNerdCoding** [comment]
再次降低优先级，有候选人试译

**Comment by BigNerdCoding** [comment]
再次开放，候选人暂时未通过

**Comment by Adolf-L** [comment]
可以重新修改提高吗？

**Comment by BigNerdCoding** [comment]
@hulizhen 在 PR 中

**Comment by Desgard** [comment]
refer https://github.com/SwiftGGTeam/translation/pull/101

**Comment by Yousanflics** [comment]
@hulizhen PR 中标记#101

**Comment by Adolf-L** [comment]
@Yousanflics 这里的 issue，我直接给你哦，因为发现在 PR 中你修改了标签。顺便问下，正常的 Process 待定稿后任务本应该移交给谁呢？
